connect moduloUsuarios/password123@chsabda_s2;

-- 
-- TABLE: BANCO 
--

CREATE TABLE BANCO(
    BANCO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE      VARCHAR2(40)     NOT NULL,
    CONSTRAINT banco_pk PRIMARY KEY (BANCO_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES
)
TABLESPACE tbs_banco
;


--
-- TABLE: CLIENTE
--

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    NOMBRE_USUARIO    VARCHAR2(40)     NOT NULL,
    PASSWORD          VARCHAR2(40)     NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    EMAIL_USUARIO     VARCHAR2(40)     NOT NULL,
    TELEFONO          VARCHAR2(40)     NOT NULL,
    DIRECCION         VARCHAR2(40)     NOT NULL,
    CONSTRAINT cliente_pk PRIMARY KEY (CLIENTE_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT cliente_tipo_chk CHECK (TIPO IN ('E','P'))
)
TABLESPACE TBS_CLIENTE
;


--
-- TABLE: ENTIDAD_NACIMIENTO
--

CREATE TABLE ENTIDAD_NACIMIENTO(
    ENTIDAD_NACIMIENTO_ID    NUMBER(5, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)    NOT NULL,
    CONSTRAINT entidad_nacimiento_pk PRIMARY KEY (ENTIDAD_NACIMIENTO_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES
)
TABLESPACE TBS_PROVEEDOR_CATALOGO
;


--
-- TABLE: NIVEL_ESTUDIO
--

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    CONSTRAINT nivel_estudio_pk PRIMARY KEY (NIVEL_ESTUDIO_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES
)
TABLESPACE TBS_PROVEEDOR_CATALOGO
;


--
-- TABLE: PROVEEDOR
--

CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(20)     NOT NULL,
    AP_PATERNO               VARCHAR2(40)     NOT NULL,
    AP_MATERNO               VARCHAR2(40)     NOT NULL,
    FOTO                     BLOB             NOT NULL,
    F_NACIMIENTO             DATE             NOT NULL,
    DIRECCION                VARCHAR2(40)     NOT NULL,
    EMAIL                    VARCHAR2(40)     NOT NULL,
    TEL_MOVIL                VARCHAR2(10)     NOT NULL,
    TEL_CASA                 VARCHAR2(10)     NOT NULL,
    IDENTIFICACION           BLOB             NOT NULL,
    C_DOMICILIO              BLOB             NOT NULL,
    ENTIDAD_NACIMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    NIVEL_ESTUDIO_ID         NUMBER(10, 0)    NOT NULL,
    PROV_REPRESENTANTE_ID    NUMBER(10, 0),
    CONSTRAINT proveedor_pk PRIMARY KEY (PROVEEDOR_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT proveedor_entidad_nacimiento_fk FOREIGN KEY (ENTIDAD_NACIMIENTO_ID)
    REFERENCES ENTIDAD_NACIMIENTO(ENTIDAD_NACIMIENTO_ID),
    CONSTRAINT proveedor_representante_fk FOREIGN KEY (PROV_REPRESENTANTE_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT proveedor_nivel_estudio_fk FOREIGN KEY (NIVEL_ESTUDIO_ID)
    REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
)
TABLESPACE TBS_PROVEEDOR
LOB (FOTO) STORE AS proveedor_foto_lob (
    TABLESPACE TBS_PROVEEDOR_LOB
    DISABLE STORAGE IN ROW
    INDEX proveedor_foto_lob_index
)
LOB (IDENTIFICACION) STORE AS proveedor_ident_lob (
    TABLESPACE TBS_PROVEEDOR_LOB
    DISABLE STORAGE IN ROW
    INDEX proveedor_ident_lob_index
)
LOB (C_DOMICILIO) STORE AS proveedor_c_domicilio_lob (
    TABLESPACE TBS_PROVEEDOR_LOB
    DISABLE STORAGE IN ROW
    INDEX proveedor_c_domicilio_lob_index
)
;


--
-- TABLE: TIPO_SERVICIO
--

CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE_SERVICIO     VARCHAR2(6)      NOT NULL,
    DESCRIPCION         VARCHAR2(40)     NOT NULL,
    CONSTRAINT tipo_servicio_pk PRIMARY KEY (TIPO_SERVICIO_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES
)
TABLESPACE TBS_PROVEEDOR_CATALOGO
;


--
-- TABLE: PROVEEDOR_SERVICIO
--

CREATE TABLE PROVEEDOR_SERVICIO(
    PROVEEDOR_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    EXPERIENCIA              NUMBER(2, 0)     NOT NULL,
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    TIPO_SERVICIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT proveedor_serviocio_pk PRIMARY KEY (PROVEEDOR_SERVICIO_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT prov_servicio_proveedor_id_fk FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT prov_servicio_tipo_servicio_fk FOREIGN KEY (TIPO_SERVICIO_ID)
    REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID)
)
TABLESPACE TBS_PROVEEDOR_SERVICIO
;


-- 
-- TABLE: COMROBANTE_EXP 
--

CREATE TABLE COMROBANTE_EXP(
    CONPROBANTE_EXP_ID       NUMBER(10, 0)    NOT NULL,
    DOCUMENTO_EXP            BLOB             NOT NULL,
    PROVEEDOR_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT comprobante_exp_pk PRIMARY KEY (CONPROBANTE_EXP_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT comprobante_exp_prov_servicio_fk FOREIGN KEY (PROVEEDOR_SERVICIO_ID)
    REFERENCES PROVEEDOR_SERVICIO(PROVEEDOR_SERVICIO_ID)
)
TABLESPACE TBS_COMPROBANTE
LOB (DOCUMENTO_EXP) STORE AS comprobante_exp_doc_lob (
    TABLESPACE TBS_COMPROBANTE_LOB
    DISABLE STORAGE IN ROW
    INDEX comprobante_exp_doc_lob_index
)
;


--
-- TABLE: CUENTA_BANCARIA
--

CREATE TABLE CUENTA_BANCARIA(
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    BANCO_ID              NUMBER(10, 0)    NOT NULL,
    CLABE                 NUMBER(18, 0)    NOT NULL,
    PROVEEDOR_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT cuenta_bancaria_pk PRIMARY KEY (CUENTA_BANCARIA_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT cuenta_bancaria_banco_fk FOREIGN KEY (BANCO_ID)
    REFERENCES BANCO(BANCO_ID),
    CONSTRAINT cuenta_bancaria_proveedor_fk FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
TABLESPACE TBS_CUENTA_BANCARIA
;



--
-- TABLE: EMPRESA
--

CREATE TABLE EMPRESA(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE_EMPRESA    VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(40)     NOT NULL,
    LOGOTIPO          BLOB             NOT NULL,
    NUM_EMPLEADOS     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT empresa_pk PRIMARY KEY (CLIENTE_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT empresa_cliente_fk FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
TABLESPACE TBS_CLIENTE
LOB (LOGOTIPO) STORE AS empresa_logo_lob (
    TABLESPACE TBS_CLIENTE_LOB
    DISABLE STORAGE IN ROW
    INDEX empresa_logo_lob_index
)
;


--
-- TABLE: PERSONA
--

CREATE TABLE PERSONA(
    CLIENTE_ID      NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(40)     NOT NULL,
    FOTO            BLOB             NOT NULL,
    CURP            VARCHAR2(18)     NOT NULL,
    F_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT persona_pk PRIMARY KEY (CLIENTE_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT persona_cliente_fk FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
TABLESPACE TBS_CLIENTE
LOB (FOTO) STORE AS persona_foto_lob (
    TABLESPACE TBS_CLIENTE_LOB
    DISABLE STORAGE IN ROW
    INDEX persona_foto_lob_index
)
;


--
-- TABLE: TARJETA
--

CREATE TABLE TARJETA(
    TARJETA_ID       NUMBER(10, 0)    NOT NULL,
    NUMERO           NUMBER(10, 0)    NOT NULL,
    ANIO_EXP         NUMBER(2, 0)     NOT NULL,
    MES_EXP          NUMBER(2, 0)     NOT NULL,
    NUM_SEGURIDAD    NUMBER(3, 0)     NOT NULL,
    CLIENTE_ID       NUMBER(10, 0)    NOT NULL,
    BANCO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT tarjeta_pk PRIMARY KEY (TARJETA_ID)
        USING INDEX TABLESPACE TBS_MOD_USUARIO_INDICES,
    CONSTRAINT tarjeta_banco_fk FOREIGN KEY (BANCO_ID)
    REFERENCES BANCO(BANCO_ID),
    CONSTRAINT tarjeta_cliente_fk FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
TABLESPACE TBS_TARJETA
;

