--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      unam
-- Project :      ProyectoFinal.DM1
-- Author :       hector
--
-- Date Created : Sunday, June 08, 2025 23:34:34
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: BANCO 
--

CREATE TABLE BANCO(
    BANCO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE      VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (BANCO_ID)
)
;



-- 
-- TABLE: STATUS_SERVICIO 
--

CREATE TABLE STATUS_SERVICIO(
    STATUS_SERVICIO_ID       NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS_SERVICIO    DATE,
    CLAVE                    VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (STATUS_SERVICIO_ID)
)
;



-- 
-- TABLE: SERVICIO 
--

CREATE TABLE SERVICIO(
    SERVICIO_ID                 NUMBER(10, 0)     NOT NULL,
    FECHA_SERVICIO              DATE              NOT NULL,
    DESCRIPCION                 VARCHAR2(1000)    NOT NULL,
    DOCUMENTO                   BLOB,
    TARJETA_ID_FK               NUMBER(10, 0)     NOT NULL,
    PROVEEDOR_SERVICIO_ID_FK    NUMBER(10, 0)     NOT NULL,
    STATUS_SERVICIO_ID          NUMBER(10, 0)     NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT RefSTATUS_SERVICIO37 FOREIGN KEY (STATUS_SERVICIO_ID)
    REFERENCES STATUS_SERVICIO(STATUS_SERVICIO_ID)
)
;



-- 
-- TABLE: SERVICIO_CONFIRMADO 
--

CREATE TABLE SERVICIO_CONFIRMADO(
    SERVICIO_ID      NUMBER(10, 0)    NOT NULL,
    PRECIO           NUMBER(40, 2)    NOT NULL,
    INSTRUCCIONES    VARCHAR2(40)     NOT NULL,
    MESUALIDADES     NUMBER(5, 0),
    DOCUMENTO        BLOB,
    CONSTRAINT PK15 PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT RefSERVICIO28 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: CALIFICACION_SERVICIO 
--

CREATE TABLE CALIFICACION_SERVICIO(
    SERVICIO_ID     NUMBER(10, 0)    NOT NULL,
    COMENTARIO      VARCHAR2(40),
    CALIFICACION    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT RefSERVICIO_CONFIRMADO45 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO_CONFIRMADO(SERVICIO_ID)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    NOMBRE_USUARIO    VARCHAR2(40)     NOT NULL,
    PASSWORD          VARCHAR2(40)     NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    EMAIL_USUARIO     VARCHAR2(40)     NOT NULL,
    TELEFONO          VARCHAR2(40)     NOT NULL,
    DIRECCION         VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: ENTIDAD_NACIMIENTO 
--

CREATE TABLE ENTIDAD_NACIMIENTO(
    ENTIDAD_NACIMIENTO_ID    NUMBER(5, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)    NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (ENTIDAD_NACIMIENTO_ID)
)
;



-- 
-- TABLE: NIVEL_ESTUDIO 
--

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (NIVEL_ESTUDIO_ID)
)
;



-- 
-- TABLE: PROVEEDOR 
--

CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(20)     NOT NULL,
    AP_PATERNO               VARCHAR2(40)     NOT NULL,
    AP_MATERNO               VARCHAR2(40)     NOT NULL,
    FOTO                     BLOB             NOT NULL,
    F_NACIMIENTO             DATE             NOT NULL,
    DIRECCION                VARCHAR2(40)     NOT NULL,
    EMAIL                    VARCHAR2(40)     NOT NULL,
    TEL_MOVIL                VARCHAR2(10)     NOT NULL,
    TEL_CASA                 VARCHAR2(10)     NOT NULL,
    IDENTIFICACION           BLOB             NOT NULL,
    C_DOMICILIO              BLOB             NOT NULL,
    ENTIDAD_NACIMIENTO_ID    NUMBER(5, 0)     NOT NULL,
    NIVEL_ESTUDIO_ID         NUMBER(10, 0)    NOT NULL,
    PROV_REPRESENTANTE_ID    NUMBER(10, 0),
    CONSTRAINT PK1 PRIMARY KEY (PROVEEDOR_ID), 
    CONSTRAINT RefENTIDAD_NACIMIENTO3 FOREIGN KEY (ENTIDAD_NACIMIENTO_ID)
    REFERENCES ENTIDAD_NACIMIENTO(ENTIDAD_NACIMIENTO_ID),
    CONSTRAINT RefPROVEEDOR14 FOREIGN KEY (PROV_REPRESENTANTE_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT RefNIVEL_ESTUDIO39 FOREIGN KEY (NIVEL_ESTUDIO_ID)
    REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID)
)
;



-- 
-- TABLE: TIPO_SERVICIO 
--

CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE_SERVICIO     VARCHAR2(6)      NOT NULL,
    DESCRIPCION         VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (TIPO_SERVICIO_ID)
)
;



-- 
-- TABLE: PROVEEDOR_SERVICIO 
--

CREATE TABLE PROVEEDOR_SERVICIO(
    PROVEEDOR_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    EXPERIENCIA              NUMBER(2, 0)     NOT NULL,
    PROVEEDOR_ID             NUMBER(10, 0)    NOT NULL,
    TIPO_SERVICIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (PROVEEDOR_SERVICIO_ID), 
    CONSTRAINT RefPROVEEDOR10 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    CONSTRAINT RefTIPO_SERVICIO11 FOREIGN KEY (TIPO_SERVICIO_ID)
    REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID)
)
;



-- 
-- TABLE: COMROBANTE_EXP 
--

CREATE TABLE COMROBANTE_EXP(
    CONPROBANTE_EXP_ID       NUMBER(10, 0)    NOT NULL,
    DOCUMENTO_EXP            BLOB             NOT NULL,
    PROVEEDOR_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (CONPROBANTE_EXP_ID), 
    CONSTRAINT RefPROVEEDOR_SERVICIO43 FOREIGN KEY (PROVEEDOR_SERVICIO_ID)
    REFERENCES PROVEEDOR_SERVICIO(PROVEEDOR_SERVICIO_ID)
)
;



-- 
-- TABLE: CUENTA_BANCARIA 
--

CREATE TABLE CUENTA_BANCARIA(
    CUENTA_BANCARIA_ID    NUMBER(10, 0)    NOT NULL,
    BANCO_ID              NUMBER(10, 0)    NOT NULL,
    CLABE                 NUMBER(18, 0)    NOT NULL,
    PROVEEDOR_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (CUENTA_BANCARIA_ID), 
    CONSTRAINT RefBANCO48 FOREIGN KEY (BANCO_ID)
    REFERENCES BANCO(BANCO_ID),
    CONSTRAINT RefPROVEEDOR8 FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID)
)
;



-- 
-- TABLE: DEPOSITO 
--

CREATE TABLE DEPOSITO(
    SERVICIO_ID       NUMBER(10, 0)    NOT NULL,
    IMPORTE           NUMBER(40, 2)    NOT NULL,
    FECHA_DEPOSITO    DATE             NOT NULL,
    COMPROBANTE       BLOB             NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (SERVICIO_ID), 
    CONSTRAINT RefSERVICIO_CONFIRMADO44 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO_CONFIRMADO(SERVICIO_ID)
)
;



-- 
-- TABLE: EMPRESA 
--

CREATE TABLE EMPRESA(
    CLIENTE_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE_EMPRESA    VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(40)     NOT NULL,
    LOGOTIPO          BLOB             NOT NULL,
    NUM_EMPLEADOS     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT RefCLIENTE18 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: EVIDENCIA 
--

CREATE TABLE EVIDENCIA(
    EVIDENCIA_ID       NUMBER(10, 0)    NOT NULL,
    NUM_CONSECUTIVO    NUMBER(3, 0)     NOT NULL,
    IMAGEN             BLOB             NOT NULL,
    DESCRIPCION        VARCHAR2(500),
    SERVICIO_ID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (EVIDENCIA_ID), 
    CONSTRAINT RefSERVICIO_CONFIRMADO46 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO_CONFIRMADO(SERVICIO_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_SERVICIO 
--

CREATE TABLE HISTORICO_STATUS_SERVICIO(
    HISTORICO_STATUS_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                    DATE             NOT NULL,
    STATUS_SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (HISTORICO_STATUS_SERVICIO_ID), 
    CONSTRAINT RefSTATUS_SERVICIO34 FOREIGN KEY (STATUS_SERVICIO_ID)
    REFERENCES STATUS_SERVICIO(STATUS_SERVICIO_ID),
    CONSTRAINT RefSERVICIO38 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: PAGO_SERVICIO 
--

CREATE TABLE PAGO_SERVICIO(
    NUM_PAGO       NUMBER(40, 0)    NOT NULL,
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO     DATE             NOT NULL,
    IMPORTE        NUMBER(40, 2)    NOT NULL,
    COMISION       NUMBER(40, 2)    NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (NUM_PAGO, SERVICIO_ID), 
    CONSTRAINT RefSERVICIO30 FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
)
;



-- 
-- TABLE: PERSONA 
--

CREATE TABLE PERSONA(
    CLIENTE_ID      NUMBER(10, 0)    NOT NULL,
    NOMBRE          VARCHAR2(40)     NOT NULL,
    FOTO            BLOB             NOT NULL,
    CURP            VARCHAR2(18)     NOT NULL,
    F_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT RefCLIENTE21 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    TARJETA_ID       NUMBER(10, 0)    NOT NULL,
    NUMERO           NUMBER(40, 0)    NOT NULL,
    ANIO_EXP         NUMBER(2, 0)     NOT NULL,
    MES_EXP          NUMBER(2, 0)     NOT NULL,
    NUM_SEGURIDAD    NUMBER(3, 0)     NOT NULL,
    CLIENTE_ID       NUMBER(10, 0)    NOT NULL,
    BANCO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (TARJETA_ID), 
    CONSTRAINT RefBANCO41 FOREIGN KEY (BANCO_ID)
    REFERENCES BANCO(BANCO_ID),
    CONSTRAINT RefCLIENTE25 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



